namespace WinUI_Presentation2
{
    [default_interface]
    runtimeclass CompositionViewControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        CompositionViewControl();
        Int32 MyProperty;
    }
}
